import Foundation

/// Describes one recognizable developer artifact directory by *name*, plus the
/// metadata needed to present it safely.
///
/// The core safety principle (borrowed from how an experienced engineer reasons
/// about this by hand): **an artifact is provably safe to delete only if the
/// tool that created it is still present and can recreate it.** We approximate
/// "the tool is present" by checking for a manifest sibling — a `package.json`
/// next to `node_modules`, a `Cargo.toml` next to `target`, etc. When the
/// manifest is missing we can't promise a clean regeneration, so the item is
/// surfaced as `.reviewRecommended` instead of auto-checked `.safe`.
struct DeveloperDetector: Sendable {
    /// Stable id and the exact directory basename to match (these are the same).
    let folderName: String
    let displayName: String
    /// Safety when the toolchain is confirmed present. May be downgraded at scan time.
    let safety: RulePack.Safety
    let reason: String
    let restoreCommand: String
    /// Manifest filenames whose presence in the *parent* directory confirms the
    /// creating toolchain. `nil` means the artifact is a pure cache with no
    /// project context required — always confirmed.
    let confirmingSiblings: [String]?

    /// True when the toolchain can be confirmed for an artifact whose parent is `parent`.
    func confirms(in parent: URL, fileManager fm: FileManager = .default) -> Bool {
        guard let siblings = confirmingSiblings else { return true }
        return siblings.contains { fm.fileExists(atPath: parent.appendingPathComponent($0).path) }
    }
}

enum DeveloperDetectors {

    /// The recognized artifact set. Ordering is irrelevant — lookups are by name.
    static let all: [DeveloperDetector] = [
        // ---- JavaScript / TypeScript ----
        DeveloperDetector(
            folderName: "node_modules", displayName: "JS dependencies",
            safety: .safe,
            reason: "Installed npm/yarn/pnpm packages — fully described by package.json.",
            restoreCommand: "npm install",
            confirmingSiblings: ["package.json"]),
        DeveloperDetector(
            folderName: ".next", displayName: "Next.js build output",
            safety: .safe,
            reason: "Next.js compiles this on every build.",
            restoreCommand: "npm run build",
            confirmingSiblings: ["package.json"]),
        DeveloperDetector(
            folderName: ".nuxt", displayName: "Nuxt build output",
            safety: .safe,
            reason: "Nuxt regenerates this on every build.",
            restoreCommand: "npm run build",
            confirmingSiblings: ["package.json"]),
        DeveloperDetector(
            folderName: ".svelte-kit", displayName: "SvelteKit build output",
            safety: .safe,
            reason: "SvelteKit regenerates this on every build.",
            restoreCommand: "npm run build",
            confirmingSiblings: ["package.json"]),
        DeveloperDetector(
            folderName: ".turbo", displayName: "Turborepo cache",
            safety: .safe,
            reason: "Turborepo task cache — rebuilt on the next run.",
            restoreCommand: "turbo run build",
            confirmingSiblings: nil),
        DeveloperDetector(
            folderName: ".parcel-cache", displayName: "Parcel cache",
            safety: .safe,
            reason: "Parcel bundler cache — rebuilt on the next build.",
            restoreCommand: "npm run build",
            confirmingSiblings: ["package.json"]),
        DeveloperDetector(
            folderName: ".expo", displayName: "Expo cache",
            safety: .safe,
            reason: "Expo dev cache — regenerated on the next start.",
            restoreCommand: "expo start",
            confirmingSiblings: ["package.json"]),
        DeveloperDetector(
            folderName: "dist", displayName: "Bundler output",
            safety: .safe,
            reason: "Build output directory — regenerated by the build script.",
            restoreCommand: "npm run build",
            confirmingSiblings: ["package.json"]),

        // ---- JVM / Android ----
        DeveloperDetector(
            folderName: "build", displayName: "Build output",
            safety: .safe,
            reason: "Gradle/Maven build output — regenerated on the next build.",
            restoreCommand: "./gradlew build",
            confirmingSiblings: ["build.gradle", "build.gradle.kts", "pom.xml"]),
        DeveloperDetector(
            folderName: ".gradle", displayName: "Gradle project cache",
            safety: .safe,
            reason: "Per-project Gradle cache — re-downloaded on the next build.",
            restoreCommand: "./gradlew build",
            confirmingSiblings: nil),
        DeveloperDetector(
            folderName: ".cxx", displayName: "Android NDK build cache",
            safety: .safe,
            reason: "Native build intermediates — regenerated on the next build.",
            restoreCommand: "./gradlew build",
            confirmingSiblings: nil),

        // ---- Rust ----
        DeveloperDetector(
            folderName: "target", displayName: "Rust build output",
            safety: .safe,
            reason: "Cargo build output — recompiled on the next build.",
            restoreCommand: "cargo build",
            confirmingSiblings: ["Cargo.toml"]),

        // ---- Flutter / Dart ----
        DeveloperDetector(
            folderName: ".dart_tool", displayName: "Dart/Flutter build cache",
            safety: .safe,
            reason: "Dart tool cache — regenerated by pub.",
            restoreCommand: "flutter pub get",
            confirmingSiblings: ["pubspec.yaml"]),

        // ---- CocoaPods ----
        DeveloperDetector(
            folderName: "Pods", displayName: "CocoaPods dependencies",
            safety: .safe,
            reason: "Installed pods — fully described by the Podfile.",
            restoreCommand: "pod install",
            confirmingSiblings: ["Podfile"]),

        // ---- Python ----
        DeveloperDetector(
            folderName: "__pycache__", displayName: "Python bytecode cache",
            safety: .safe,
            reason: "Compiled .pyc files — regenerated automatically on import.",
            restoreCommand: "(automatic)",
            confirmingSiblings: nil),
        DeveloperDetector(
            folderName: ".pytest_cache", displayName: "pytest cache",
            safety: .safe,
            reason: "Test run cache — regenerated by pytest.",
            restoreCommand: "pytest",
            confirmingSiblings: nil),
        DeveloperDetector(
            folderName: ".mypy_cache", displayName: "mypy cache",
            safety: .safe,
            reason: "Type-check cache — regenerated by mypy.",
            restoreCommand: "mypy .",
            confirmingSiblings: nil),
        DeveloperDetector(
            folderName: ".ruff_cache", displayName: "Ruff cache",
            safety: .safe,
            reason: "Lint cache — regenerated by Ruff.",
            restoreCommand: "ruff check .",
            confirmingSiblings: nil),
        // Virtual environments are recreatable but doing so re-downloads every
        // dependency and can be slow — a deliberate per-project decision, so we
        // surface them as review-recommended rather than auto-checking them.
        DeveloperDetector(
            folderName: "venv", displayName: "Python virtual environment",
            safety: .reviewRecommended,
            reason: "Project virtualenv — recreatable, but re-downloads all packages.",
            restoreCommand: "python3 -m venv venv && pip install -r requirements.txt",
            confirmingSiblings: nil),
        DeveloperDetector(
            folderName: ".venv", displayName: "Python virtual environment",
            safety: .reviewRecommended,
            reason: "Project virtualenv — recreatable, but re-downloads all packages.",
            restoreCommand: "python3 -m venv .venv && pip install -r requirements.txt",
            confirmingSiblings: nil),
        DeveloperDetector(
            folderName: ".tox", displayName: "tox environments",
            safety: .reviewRecommended,
            reason: "tox test environments — recreated on the next run.",
            restoreCommand: "tox",
            confirmingSiblings: nil),
    ]

    private static let byName: [String: DeveloperDetector] =
        Dictionary(uniqueKeysWithValues: all.map { ($0.folderName, $0) })

    static func match(folderName: String) -> DeveloperDetector? { byName[folderName] }
}
